wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706088015.498657
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
